⬆️ (deps)`swr@1.2.1` 👷️ (actions) updates for dependa🤖  (#869)
Bumps [swr](https://github.com/vercel/swr) from 1.2.0 to 1.2.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/vercel/swr/releases">swr's releases</a>.</em></p>
<blockquote>
<h2>1.2.1</h2>
<h2>Highlights of This Release</h2>
<h3><code>shouldRetryOnError</code> accepts a function</h3>
<p>Previously <a href="https://swr.vercel.app/docs/error-handling#error-retry"><code>shouldRetryOnError</code></a> is either true or false. Now it accepts a function that conditionally determines if SWR should retry. Here's a simple example:</p>
<pre lang="js"><code>const fetcher = url =&gt; fetch(url).then(res =&gt; {
  // Fetcher throws if the response code is not 2xx.
  if (!res.ok) throw res
  return res.json()
})
<p>useSWR(key, fetcher, {
shouldRetryOnError: (error) =&gt; {
// We skip retrying if the API is returning 404:
if (error.status === 404) return false
return true
}
})
</code></pre></p>
<p>Thanks to <a href="https://github.com/sairajchouhan"><code>@​sairajchouhan</code></a> for contributing!</p>
<h2>What's Changed</h2>
<ul>
<li><code>shouldRetryOnError</code> accepts a function that can be used to conditionally stop retrying   by <a href="https://github.com/sairajchouhan"><code>@​sairajchouhan</code></a> in <a href="https://github-redirect.dependabot.com/vercel/swr/pull/1816">vercel/swr#1816</a></li>
<li>build(deps-dev): bump next from 12.0.8 to 12.0.9 by <a href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a href="https://github-redirect.dependabot.com/vercel/swr/pull/1821">vercel/swr#1821</a></li>
<li>fix: useSWRInfinite revalidates with revalidateOnMount by <a href="https://github.com/koba04"><code>@​koba04</code></a> in <a href="https://github-redirect.dependabot.com/vercel/swr/pull/1830">vercel/swr#1830</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/sairajchouhan"><code>@​sairajchouhan</code></a> made their first contribution in <a href="https://github-redirect.dependabot.com/vercel/swr/pull/1816">vercel/swr#1816</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a href="https://github.com/vercel/swr/compare/1.2.0...1.2.1">https://github.com/vercel/swr/compare/1.2.0...1.2.1</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/vercel/swr/commit/c63cafcb00f78af1d16ef5649d7c26d396c46de9"><code>c63cafc</code></a> 1.2.1</li>
<li><a href="https://github.com/vercel/swr/commit/922048e44e5dd3cd6e0ab8c401bebc0a6c4ec70b"><code>922048e</code></a> fix: useSWRInfinite revalidates with revalidateOnMount (<a href="https://github-redirect.dependabot.com/vercel/swr/issues/1830">#1830</a>)</li>
<li><a href="https://github.com/vercel/swr/commit/a4ab0c9edc380728d72a41a288bd71882926b6e7"><code>a4ab0c9</code></a> build(deps-dev): bump next from 12.0.8 to 12.0.9 (<a href="https://github-redirect.dependabot.com/vercel/swr/issues/1821">#1821</a>)</li>
<li><a href="https://github.com/vercel/swr/commit/53dc100c35daf8fe6f033c81e42164d667f2f85f"><code>53dc100</code></a> feat: shouldErrorRetry accepts a function (<a href="https://github-redirect.dependabot.com/vercel/swr/issues/1816">#1816</a>)</li>
<li>See full diff in <a href="https://github.com/vercel/swr/compare/1.2.0...1.2.1">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=swr&package-manager=npm_and_yarn&previous-version=1.2.0&new-version=1.2.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>